server:
  port: ${PORT:5000}
ff4j:
  audit:
    enabled: true
  security:
    enabled: true
  web-console:
    enabled: true
    context-path: /ff4j-web
    security:
      enabled: true
      username: admin
      password: admin
  springdoc:
    enabled: true
springdoc:
  swagger-ui:
    tags-sorter: "alpha"
    operations-sorter: "alpha"